import os

import google.generativeai as genai

genai.configure(api_key=os.getenv("GOOGLEAI_API_KEY"))
model = genai.GenerativeModel("gemini-2.0-flash")

disclaimer = "\n<i>Generated by AI (Google Gemini 2.0)</i>"
error_message = "<i>This feature is temporarily unavailable</i>"


def explainSong(lyrics):
    response = ""
    try:
        response = model.generate_content(
            ["Explain this hymn in up to 7 lines", lyrics]
        ).text
        response += disclaimer
    except:
        return error_message
    return response
