from google import genai

client = genai.Client()

disclaimer = "\n\n<i>Generated by AI (Google Gemini 2.5)</i>"
error_message = "<i>This feature is temporarily unavailable</i>"


def explainSong(lyrics):
    response = ""
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash-lite",
            contents=["Explain this hymn in up to 7 lines", lyrics],
        ).text
        response += disclaimer
    except:
        response = error_message
    return response
